#!/usr/bin/env php
<?php

include_once "vendor/autoload.php";

use GuzzleHttp\Exception\GuzzleException;

$appUrl = getVar('APP_URL', '');
$prodUrl = getVar('PRODUCT_URL', $appUrl);
$appEnv = getVar('ENV', 'development');
$files = glob('resources/views/*.blade.php');

if (file_exists('compiles/routes.txt')) {
	unlink('compiles/routes.txt');
}

foreach ($files as $file) {
	$filename = basename($file, '.blade.php');
	echo "Generate page: {$appUrl}/{$filename}.html\n";
	$client = new GuzzleHttp\Client();
	
	try {
        $client->request('GET', "{$appUrl}/?f={$filename}&build");
		$file = fopen("compiles/routes.txt", "a");
        if ($filename !== '404') {
            fwrite($file, "{$prodUrl}/{$filename}.html\n");
        }
		fclose($file);
	} catch (GuzzleException $e) {
		echo "Error: " . $e->getMessage() . "\n";
	}
}

exec('cp -r resources/assets compiles/assets');
exec('rm -rf compiles/404.html');
exec('find compiles -name .gitkeep -exec rm -f {} \;');
exec('rm -rf compiles/assets/scss');
echo "Build complete\n";
