#!/usr/bin/env php
<?php

include_once "vendor/autoload.php";

use GuzzleHttp\Exception\GuzzleException;

$appUrl = getVar('APP_URL');
$files = glob('resources/views/*.blade.php');
foreach ($files as $file) {
	$filename = basename($file, '.blade.php');
	echo "Generate page: $appUrl/$filename.html\n";
	$client = new GuzzleHttp\Client();
	
	try {
		$client->request('GET', "$appUrl/$filename.html?build");
	} catch (GuzzleException $e) {
		echo "Error: " . $e->getMessage() . "\n";
	}
}

exec('cp -r resources/assets compiles/assets');
exec('zip -r compiles.zip compiles');
echo "Build complete\n";
